	pcie_reconfig u0 (
		.config_tl_hpg_ctrler             (<connected-to-config_tl_hpg_ctrler>),             //      config_tl.hpg_ctrler
		.config_tl_tl_cfg_ctl             (<connected-to-config_tl_tl_cfg_ctl>),             //               .tl_cfg_ctl
		.config_tl_cpl_err                (<connected-to-config_tl_cpl_err>),                //               .cpl_err
		.config_tl_tl_cfg_add             (<connected-to-config_tl_tl_cfg_add>),             //               .tl_cfg_add
		.config_tl_tl_cfg_ctl_wr          (<connected-to-config_tl_tl_cfg_ctl_wr>),          //               .tl_cfg_ctl_wr
		.config_tl_tl_cfg_sts_wr          (<connected-to-config_tl_tl_cfg_sts_wr>),          //               .tl_cfg_sts_wr
		.config_tl_tl_cfg_sts             (<connected-to-config_tl_tl_cfg_sts>),             //               .tl_cfg_sts
		.config_tl_cpl_pending            (<connected-to-config_tl_cpl_pending>),            //               .cpl_pending
		.coreclkout_hip_clk               (<connected-to-coreclkout_hip_clk>),               // coreclkout_hip.clk
		.hip_ctrl_test_in                 (<connected-to-hip_ctrl_test_in>),                 //       hip_ctrl.test_in
		.hip_ctrl_simu_mode_pipe          (<connected-to-hip_ctrl_simu_mode_pipe>),          //               .simu_mode_pipe
		.hip_pipe_sim_pipe_pclk_in        (<connected-to-hip_pipe_sim_pipe_pclk_in>),        //       hip_pipe.sim_pipe_pclk_in
		.hip_pipe_sim_pipe_rate           (<connected-to-hip_pipe_sim_pipe_rate>),           //               .sim_pipe_rate
		.hip_pipe_sim_ltssmstate          (<connected-to-hip_pipe_sim_ltssmstate>),          //               .sim_ltssmstate
		.hip_pipe_eidleinfersel0          (<connected-to-hip_pipe_eidleinfersel0>),          //               .eidleinfersel0
		.hip_pipe_eidleinfersel1          (<connected-to-hip_pipe_eidleinfersel1>),          //               .eidleinfersel1
		.hip_pipe_eidleinfersel2          (<connected-to-hip_pipe_eidleinfersel2>),          //               .eidleinfersel2
		.hip_pipe_eidleinfersel3          (<connected-to-hip_pipe_eidleinfersel3>),          //               .eidleinfersel3
		.hip_pipe_powerdown0              (<connected-to-hip_pipe_powerdown0>),              //               .powerdown0
		.hip_pipe_powerdown1              (<connected-to-hip_pipe_powerdown1>),              //               .powerdown1
		.hip_pipe_powerdown2              (<connected-to-hip_pipe_powerdown2>),              //               .powerdown2
		.hip_pipe_powerdown3              (<connected-to-hip_pipe_powerdown3>),              //               .powerdown3
		.hip_pipe_rxpolarity0             (<connected-to-hip_pipe_rxpolarity0>),             //               .rxpolarity0
		.hip_pipe_rxpolarity1             (<connected-to-hip_pipe_rxpolarity1>),             //               .rxpolarity1
		.hip_pipe_rxpolarity2             (<connected-to-hip_pipe_rxpolarity2>),             //               .rxpolarity2
		.hip_pipe_rxpolarity3             (<connected-to-hip_pipe_rxpolarity3>),             //               .rxpolarity3
		.hip_pipe_txcompl0                (<connected-to-hip_pipe_txcompl0>),                //               .txcompl0
		.hip_pipe_txcompl1                (<connected-to-hip_pipe_txcompl1>),                //               .txcompl1
		.hip_pipe_txcompl2                (<connected-to-hip_pipe_txcompl2>),                //               .txcompl2
		.hip_pipe_txcompl3                (<connected-to-hip_pipe_txcompl3>),                //               .txcompl3
		.hip_pipe_txdata0                 (<connected-to-hip_pipe_txdata0>),                 //               .txdata0
		.hip_pipe_txdata1                 (<connected-to-hip_pipe_txdata1>),                 //               .txdata1
		.hip_pipe_txdata2                 (<connected-to-hip_pipe_txdata2>),                 //               .txdata2
		.hip_pipe_txdata3                 (<connected-to-hip_pipe_txdata3>),                 //               .txdata3
		.hip_pipe_txdatak0                (<connected-to-hip_pipe_txdatak0>),                //               .txdatak0
		.hip_pipe_txdatak1                (<connected-to-hip_pipe_txdatak1>),                //               .txdatak1
		.hip_pipe_txdatak2                (<connected-to-hip_pipe_txdatak2>),                //               .txdatak2
		.hip_pipe_txdatak3                (<connected-to-hip_pipe_txdatak3>),                //               .txdatak3
		.hip_pipe_txdetectrx0             (<connected-to-hip_pipe_txdetectrx0>),             //               .txdetectrx0
		.hip_pipe_txdetectrx1             (<connected-to-hip_pipe_txdetectrx1>),             //               .txdetectrx1
		.hip_pipe_txdetectrx2             (<connected-to-hip_pipe_txdetectrx2>),             //               .txdetectrx2
		.hip_pipe_txdetectrx3             (<connected-to-hip_pipe_txdetectrx3>),             //               .txdetectrx3
		.hip_pipe_txelecidle0             (<connected-to-hip_pipe_txelecidle0>),             //               .txelecidle0
		.hip_pipe_txelecidle1             (<connected-to-hip_pipe_txelecidle1>),             //               .txelecidle1
		.hip_pipe_txelecidle2             (<connected-to-hip_pipe_txelecidle2>),             //               .txelecidle2
		.hip_pipe_txelecidle3             (<connected-to-hip_pipe_txelecidle3>),             //               .txelecidle3
		.hip_pipe_txswing0                (<connected-to-hip_pipe_txswing0>),                //               .txswing0
		.hip_pipe_txswing1                (<connected-to-hip_pipe_txswing1>),                //               .txswing1
		.hip_pipe_txswing2                (<connected-to-hip_pipe_txswing2>),                //               .txswing2
		.hip_pipe_txswing3                (<connected-to-hip_pipe_txswing3>),                //               .txswing3
		.hip_pipe_txmargin0               (<connected-to-hip_pipe_txmargin0>),               //               .txmargin0
		.hip_pipe_txmargin1               (<connected-to-hip_pipe_txmargin1>),               //               .txmargin1
		.hip_pipe_txmargin2               (<connected-to-hip_pipe_txmargin2>),               //               .txmargin2
		.hip_pipe_txmargin3               (<connected-to-hip_pipe_txmargin3>),               //               .txmargin3
		.hip_pipe_txdeemph0               (<connected-to-hip_pipe_txdeemph0>),               //               .txdeemph0
		.hip_pipe_txdeemph1               (<connected-to-hip_pipe_txdeemph1>),               //               .txdeemph1
		.hip_pipe_txdeemph2               (<connected-to-hip_pipe_txdeemph2>),               //               .txdeemph2
		.hip_pipe_txdeemph3               (<connected-to-hip_pipe_txdeemph3>),               //               .txdeemph3
		.hip_pipe_phystatus0              (<connected-to-hip_pipe_phystatus0>),              //               .phystatus0
		.hip_pipe_phystatus1              (<connected-to-hip_pipe_phystatus1>),              //               .phystatus1
		.hip_pipe_phystatus2              (<connected-to-hip_pipe_phystatus2>),              //               .phystatus2
		.hip_pipe_phystatus3              (<connected-to-hip_pipe_phystatus3>),              //               .phystatus3
		.hip_pipe_rxdata0                 (<connected-to-hip_pipe_rxdata0>),                 //               .rxdata0
		.hip_pipe_rxdata1                 (<connected-to-hip_pipe_rxdata1>),                 //               .rxdata1
		.hip_pipe_rxdata2                 (<connected-to-hip_pipe_rxdata2>),                 //               .rxdata2
		.hip_pipe_rxdata3                 (<connected-to-hip_pipe_rxdata3>),                 //               .rxdata3
		.hip_pipe_rxdatak0                (<connected-to-hip_pipe_rxdatak0>),                //               .rxdatak0
		.hip_pipe_rxdatak1                (<connected-to-hip_pipe_rxdatak1>),                //               .rxdatak1
		.hip_pipe_rxdatak2                (<connected-to-hip_pipe_rxdatak2>),                //               .rxdatak2
		.hip_pipe_rxdatak3                (<connected-to-hip_pipe_rxdatak3>),                //               .rxdatak3
		.hip_pipe_rxelecidle0             (<connected-to-hip_pipe_rxelecidle0>),             //               .rxelecidle0
		.hip_pipe_rxelecidle1             (<connected-to-hip_pipe_rxelecidle1>),             //               .rxelecidle1
		.hip_pipe_rxelecidle2             (<connected-to-hip_pipe_rxelecidle2>),             //               .rxelecidle2
		.hip_pipe_rxelecidle3             (<connected-to-hip_pipe_rxelecidle3>),             //               .rxelecidle3
		.hip_pipe_rxstatus0               (<connected-to-hip_pipe_rxstatus0>),               //               .rxstatus0
		.hip_pipe_rxstatus1               (<connected-to-hip_pipe_rxstatus1>),               //               .rxstatus1
		.hip_pipe_rxstatus2               (<connected-to-hip_pipe_rxstatus2>),               //               .rxstatus2
		.hip_pipe_rxstatus3               (<connected-to-hip_pipe_rxstatus3>),               //               .rxstatus3
		.hip_pipe_rxvalid0                (<connected-to-hip_pipe_rxvalid0>),                //               .rxvalid0
		.hip_pipe_rxvalid1                (<connected-to-hip_pipe_rxvalid1>),                //               .rxvalid1
		.hip_pipe_rxvalid2                (<connected-to-hip_pipe_rxvalid2>),                //               .rxvalid2
		.hip_pipe_rxvalid3                (<connected-to-hip_pipe_rxvalid3>),                //               .rxvalid3
		.hip_rst_reset_status             (<connected-to-hip_rst_reset_status>),             //        hip_rst.reset_status
		.hip_rst_serdes_pll_locked        (<connected-to-hip_rst_serdes_pll_locked>),        //               .serdes_pll_locked
		.hip_rst_pld_clk_inuse            (<connected-to-hip_rst_pld_clk_inuse>),            //               .pld_clk_inuse
		.hip_rst_pld_core_ready           (<connected-to-hip_rst_pld_core_ready>),           //               .pld_core_ready
		.hip_rst_testin_zero              (<connected-to-hip_rst_testin_zero>),              //               .testin_zero
		.hip_serial_rx_in0                (<connected-to-hip_serial_rx_in0>),                //     hip_serial.rx_in0
		.hip_serial_rx_in1                (<connected-to-hip_serial_rx_in1>),                //               .rx_in1
		.hip_serial_rx_in2                (<connected-to-hip_serial_rx_in2>),                //               .rx_in2
		.hip_serial_rx_in3                (<connected-to-hip_serial_rx_in3>),                //               .rx_in3
		.hip_serial_tx_out0               (<connected-to-hip_serial_tx_out0>),               //               .tx_out0
		.hip_serial_tx_out1               (<connected-to-hip_serial_tx_out1>),               //               .tx_out1
		.hip_serial_tx_out2               (<connected-to-hip_serial_tx_out2>),               //               .tx_out2
		.hip_serial_tx_out3               (<connected-to-hip_serial_tx_out3>),               //               .tx_out3
		.hip_status_derr_cor_ext_rcv      (<connected-to-hip_status_derr_cor_ext_rcv>),      //     hip_status.derr_cor_ext_rcv
		.hip_status_derr_cor_ext_rpl      (<connected-to-hip_status_derr_cor_ext_rpl>),      //               .derr_cor_ext_rpl
		.hip_status_derr_rpl              (<connected-to-hip_status_derr_rpl>),              //               .derr_rpl
		.hip_status_dlup_exit             (<connected-to-hip_status_dlup_exit>),             //               .dlup_exit
		.hip_status_ltssmstate            (<connected-to-hip_status_ltssmstate>),            //               .ltssmstate
		.hip_status_ev128ns               (<connected-to-hip_status_ev128ns>),               //               .ev128ns
		.hip_status_ev1us                 (<connected-to-hip_status_ev1us>),                 //               .ev1us
		.hip_status_hotrst_exit           (<connected-to-hip_status_hotrst_exit>),           //               .hotrst_exit
		.hip_status_int_status            (<connected-to-hip_status_int_status>),            //               .int_status
		.hip_status_l2_exit               (<connected-to-hip_status_l2_exit>),               //               .l2_exit
		.hip_status_lane_act              (<connected-to-hip_status_lane_act>),              //               .lane_act
		.hip_status_ko_cpl_spc_header     (<connected-to-hip_status_ko_cpl_spc_header>),     //               .ko_cpl_spc_header
		.hip_status_ko_cpl_spc_data       (<connected-to-hip_status_ko_cpl_spc_data>),       //               .ko_cpl_spc_data
		.hip_status_drv_derr_cor_ext_rcv  (<connected-to-hip_status_drv_derr_cor_ext_rcv>),  // hip_status_drv.derr_cor_ext_rcv
		.hip_status_drv_derr_cor_ext_rpl  (<connected-to-hip_status_drv_derr_cor_ext_rpl>),  //               .derr_cor_ext_rpl
		.hip_status_drv_derr_rpl          (<connected-to-hip_status_drv_derr_rpl>),          //               .derr_rpl
		.hip_status_drv_dlup_exit         (<connected-to-hip_status_drv_dlup_exit>),         //               .dlup_exit
		.hip_status_drv_ev128ns           (<connected-to-hip_status_drv_ev128ns>),           //               .ev128ns
		.hip_status_drv_ev1us             (<connected-to-hip_status_drv_ev1us>),             //               .ev1us
		.hip_status_drv_hotrst_exit       (<connected-to-hip_status_drv_hotrst_exit>),       //               .hotrst_exit
		.hip_status_drv_int_status        (<connected-to-hip_status_drv_int_status>),        //               .int_status
		.hip_status_drv_l2_exit           (<connected-to-hip_status_drv_l2_exit>),           //               .l2_exit
		.hip_status_drv_lane_act          (<connected-to-hip_status_drv_lane_act>),          //               .lane_act
		.hip_status_drv_ltssmstate        (<connected-to-hip_status_drv_ltssmstate>),        //               .ltssmstate
		.hip_status_drv_ko_cpl_spc_header (<connected-to-hip_status_drv_ko_cpl_spc_header>), //               .ko_cpl_spc_header
		.hip_status_drv_ko_cpl_spc_data   (<connected-to-hip_status_drv_ko_cpl_spc_data>),   //               .ko_cpl_spc_data
		.int_msi_app_msi_num              (<connected-to-int_msi_app_msi_num>),              //        int_msi.app_msi_num
		.int_msi_app_msi_req              (<connected-to-int_msi_app_msi_req>),              //               .app_msi_req
		.int_msi_app_msi_tc               (<connected-to-int_msi_app_msi_tc>),               //               .app_msi_tc
		.int_msi_app_msi_ack              (<connected-to-int_msi_app_msi_ack>),              //               .app_msi_ack
		.int_msi_app_int_sts              (<connected-to-int_msi_app_int_sts>),              //               .app_int_sts
		.lmi_lmi_addr                     (<connected-to-lmi_lmi_addr>),                     //            lmi.lmi_addr
		.lmi_lmi_din                      (<connected-to-lmi_lmi_din>),                      //               .lmi_din
		.lmi_lmi_rden                     (<connected-to-lmi_lmi_rden>),                     //               .lmi_rden
		.lmi_lmi_wren                     (<connected-to-lmi_lmi_wren>),                     //               .lmi_wren
		.lmi_lmi_ack                      (<connected-to-lmi_lmi_ack>),                      //               .lmi_ack
		.lmi_lmi_dout                     (<connected-to-lmi_lmi_dout>),                     //               .lmi_dout
		.npor_npor                        (<connected-to-npor_npor>),                        //           npor.npor
		.npor_pin_perst                   (<connected-to-npor_pin_perst>),                   //               .pin_perst
		.pld_clk_clk                      (<connected-to-pld_clk_clk>),                      //        pld_clk.clk
		.pld_clk_1_clk                    (<connected-to-pld_clk_1_clk>),                    //      pld_clk_1.clk
		.power_mngt_pm_auxpwr             (<connected-to-power_mngt_pm_auxpwr>),             //     power_mngt.pm_auxpwr
		.power_mngt_pm_data               (<connected-to-power_mngt_pm_data>),               //               .pm_data
		.power_mngt_pme_to_cr             (<connected-to-power_mngt_pme_to_cr>),             //               .pme_to_cr
		.power_mngt_pm_event              (<connected-to-power_mngt_pm_event>),              //               .pm_event
		.power_mngt_pme_to_sr             (<connected-to-power_mngt_pme_to_sr>),             //               .pme_to_sr
		.reconfig_clk_clk                 (<connected-to-reconfig_clk_clk>),                 //   reconfig_clk.clk
		.reconfig_reset_reset_n           (<connected-to-reconfig_reset_reset_n>),           // reconfig_reset.reset_n
		.refclk_clk                       (<connected-to-refclk_clk>),                       //         refclk.clk
		.rx_bar_be_rx_st_bar              (<connected-to-rx_bar_be_rx_st_bar>),              //      rx_bar_be.rx_st_bar
		.rx_bar_be_rx_st_mask             (<connected-to-rx_bar_be_rx_st_mask>),             //               .rx_st_mask
		.rx_st_valid                      (<connected-to-rx_st_valid>),                      //          rx_st.valid
		.rx_st_startofpacket              (<connected-to-rx_st_startofpacket>),              //               .startofpacket
		.rx_st_endofpacket                (<connected-to-rx_st_endofpacket>),                //               .endofpacket
		.rx_st_ready                      (<connected-to-rx_st_ready>),                      //               .ready
		.rx_st_error                      (<connected-to-rx_st_error>),                      //               .error
		.rx_st_data                       (<connected-to-rx_st_data>),                       //               .data
		.tx_cred_tx_cred_datafccp         (<connected-to-tx_cred_tx_cred_datafccp>),         //        tx_cred.tx_cred_datafccp
		.tx_cred_tx_cred_datafcnp         (<connected-to-tx_cred_tx_cred_datafcnp>),         //               .tx_cred_datafcnp
		.tx_cred_tx_cred_datafcp          (<connected-to-tx_cred_tx_cred_datafcp>),          //               .tx_cred_datafcp
		.tx_cred_tx_cred_fchipcons        (<connected-to-tx_cred_tx_cred_fchipcons>),        //               .tx_cred_fchipcons
		.tx_cred_tx_cred_fcinfinite       (<connected-to-tx_cred_tx_cred_fcinfinite>),       //               .tx_cred_fcinfinite
		.tx_cred_tx_cred_hdrfccp          (<connected-to-tx_cred_tx_cred_hdrfccp>),          //               .tx_cred_hdrfccp
		.tx_cred_tx_cred_hdrfcnp          (<connected-to-tx_cred_tx_cred_hdrfcnp>),          //               .tx_cred_hdrfcnp
		.tx_cred_tx_cred_hdrfcp           (<connected-to-tx_cred_tx_cred_hdrfcp>),           //               .tx_cred_hdrfcp
		.tx_fifo_fifo_empty               (<connected-to-tx_fifo_fifo_empty>),               //        tx_fifo.fifo_empty
		.tx_st_valid                      (<connected-to-tx_st_valid>),                      //          tx_st.valid
		.tx_st_startofpacket              (<connected-to-tx_st_startofpacket>),              //               .startofpacket
		.tx_st_endofpacket                (<connected-to-tx_st_endofpacket>),                //               .endofpacket
		.tx_st_ready                      (<connected-to-tx_st_ready>),                      //               .ready
		.tx_st_error                      (<connected-to-tx_st_error>),                      //               .error
		.tx_st_data                       (<connected-to-tx_st_data>)                        //               .data
	);

